server:
  port: 50305

newrelic:
  appname: mumbai.mt.linkit360.com
  license: 4d635427ad90ca786ca2db6aa246ed651730b933

service:
  subscriptions_period: 600
  retry_period: 600
  db:
    conn_ttl: -1
    max_conns: 15
    timeout: 30
    name: linkit_dev
    user: linkit
    pass: E0kZN8pUAs63wePepf
    port: 5432
    host: linkit.cz3twmoynbq5.eu-central-1.rds.amazonaws.com
    ssl_mode: disable
    table_prefix: xmp_

  tables:
  - subscriptions

  mobilink:
    enabled: true
    location: Asia/Karachi
    connection:
      mt:
        url: http://182.16.255.46:10020/Air
        headers:
          Content-Type: text/xml
          Authorization: Basic SU5UTE5LVVI6TGluayMwMTAx
          User-Agent: MEGASTORE_RPC/4.1/1.0
          Cache-Control: no-cache
          Pragma: no-cache
          Host: 182.16.255.46:10020
          Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2

        timeout: 20
        ok_body_contains:
          - <value><i4>0</i4></value>

      smpp:
        short_number: 4162
        endpoint: 182.16.255.46:15019
        user: SLYEPPLA
        pass: SLYPEE_1
        timeout: 30
    mt_body: |
      <?xml version="1.0" encoding="UTF-8"?>
      <methodCall>
      <methodName>UpdateBalanceAndDate</methodName>
      <params>
        <param>
          <value>
            <struct>
              <member>
                <name>originNodeType</name>
                <value>
                  <string>EXT</string>
                </value>
              </member>
              <member>
                <name>originHostName</name>
                <value>
                  <string>megastore</string>
                </value>
              </member>
              <member>
                <name>originTransactionID</name>
                <value>
                  <string>%token%</string>
                </value>
              </member>
              <member>
                <name>originTimeStamp</name>
                <value>
                  <dateTime.iso8601>%time%</dateTime.iso8601>
                </value>
              </member>
              <member>
                <name>subscriberNumber</name>
                <value>
                  <string>%msisdn%</string>
                </value>
              </member>
              <member>
                <name>transactionCurrency</name>
                <value>
                  <string>PKR</string>
                </value>
              </member>
              <member>
                <name>adjustmentAmountRelative</name>
                <value>
                  <string>%price%</string>
                </value>
              </member>
              <member>
                <name>externalData2</name>
                <value>
                  <string>megastore_VAS</string>
                </value>
              </member>
              <member>
                <name>externalData1</name>
                <value>
                  <string>megastore_VAS</string>
                </value>
              </member>
              <member>
                <name>refillProfileID</name>
                <value>
                  <string>NA</string>
                </value>
              </member>
              <member>
                <name>transactionType</name>
                <value>
                  <string>megastore</string>
                </value>
              </member>
              <member>
                <name>transactionCode</name>
                <value>
                  <string>megastore</string>
                </value>
              </member>
            </struct>
          </value>
        </param>
      </params>
      </methodCall>